services:
  api:
    build: ./backend/
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
    environment:
      - FLASK_DEBUG=true
      - PYTHONUNBUFFERED=1
    networks:
      - ats-network

  client:
    build: ./frontend/
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    environment:
      - WATCHPACK_POLLING=true
    networks:
      - ats-network

  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - 4444:4444
    shm_size: 2g

networks:
  ats-network:
    driver: bridge
