services:
    api:
        build:
            context: .
            dockerfile: backend/dockerfile.api
        image: ats-api
        ports:
            - '5000:5000'
        networks:
            - ats-network
    client:
        build:
            context: .
            dockerfile: backend/dockerfile.client
        image: ats-client
        ports:
            - '3000:3000'
        networks:
            - ats-network
        volumes:
          - type: bind
            source: /frontend
            target: /src
        environment:
            - WATCHPACK_POLLING=true

networks:
    ats-network:
        driver: bridge