services:
  api:
    build: ./backend/
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
    environment:
      - FLASK_DEBUG=true
    networks:
      - ats-network

  client:
    build: ./frontend/
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    environment:
      - WATCHPACK_POLLING=true
    networks:
      - ats-network

networks:
  ats-network:
    driver: bridge
